# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1e5b8c58e9ee9970957e36189fd2489f102d489a51b125743e78534b3c84198dda140614869f836171221e03f6766165aa5eb45a7d71915e4b56417b628065d7

# Use different runs of `rake secret` for development and test
test:
  secret_key_base: 2dea6f275fcca2955b11daf75ced973e79322990d7c17aa948665645aec00d31d4503b5a004f7a73aaa4b7aca29b91337b628af87878801929d45a47b0304058

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
